# Generated by Django 4.1.5 on 2023-01-15 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='decription',
            new_name='description',
        ),
    ]
